name: "NeedBee"
description: "Programming programs."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

sass:
  style: compressed

exclude: ["node_modules","scss","README.md","*.json","Gruntfile.js"]
